// AUTO-GENERATED from "inventory (1).xlsx" — do not edit by hand.
// Regenerate rather than patching: every field mirrors a spreadsheet column.
//
// Sheets: servers (23), workstations (15), components (17) = 55 products.
// Prices are real and come from the sheet, so products seed ACTIVE.
//
// `imageFile` holds the path the sheet specifies (e.g. "/images/dell-r760.jpg").
// No such files exist in public/ today, so the seed only attaches an image when
// the file is actually present on disk — otherwise the storefront would render
// broken images across the whole catalogue. Drop the files into public/images/
// and re-seed to attach them, or upload per-product via Admin → Products.
//
// Not in the sheet: stock (defaults to 10) and any tier/configuration data,
// so no ProductTiers are created. Each product has one fixed build, seeded as
// single-value option groups so the specs render on the product page.

export type SeedOptionGroup = {
  name: string; label: string; sortOrder: number;
  /** The single spec this product ships with; the sheet lists no alternatives. */
  value: string;
};

export type SeedCategory = {
  slug: string; name: string; description: string | null;
  parent: string | null; sortOrder: number;
};

export type SeedProduct = {
  sku: string; name: string; slug: string; brand: string;
  categorySlug: string; shortDesc: string; description: string;
  basePrice: number; warranty: string | null; imageFile: string | null;
  isFeatured: boolean; groups: SeedOptionGroup[];
};

export const categories: SeedCategory[] = [
  {
    "slug": "servers",
    "name": "Servers",
    "description": "Enterprise rack and tower servers from Dell, HPE, HP and Lenovo",
    "parent": null,
    "sortOrder": 0
  },
  {
    "slug": "rack-servers",
    "name": "Rack Servers",
    "description": null,
    "parent": "servers",
    "sortOrder": 0
  },
  {
    "slug": "tower-servers",
    "name": "Tower Servers",
    "description": null,
    "parent": "servers",
    "sortOrder": 1
  },
  {
    "slug": "workstations",
    "name": "Workstations",
    "description": "Professional workstations for engineering, rendering and simulation",
    "parent": null,
    "sortOrder": 1
  },
  {
    "slug": "components",
    "name": "Components",
    "description": "Processors, memory, controllers, network cards and workstation GPUs",
    "parent": null,
    "sortOrder": 2
  },
  {
    "slug": "processors",
    "name": "Processors",
    "description": null,
    "parent": "components",
    "sortOrder": 0
  },
  {
    "slug": "memory",
    "name": "Memory",
    "description": null,
    "parent": "components",
    "sortOrder": 1
  },
  {
    "slug": "raid-controllers",
    "name": "RAID Controllers",
    "description": null,
    "parent": "components",
    "sortOrder": 2
  },
  {
    "slug": "network-cards",
    "name": "Network Cards",
    "description": null,
    "parent": "components",
    "sortOrder": 3
  },
  {
    "slug": "workstation-gpus",
    "name": "Workstation GPUs",
    "description": null,
    "parent": "components",
    "sortOrder": 4
  }
];

export const products: SeedProduct[] = [
  {
    sku: "PE-R760",
    name: "Dell PowerEdge R760",
    slug: "dell-r760",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "16th Gen 2U rack server for AI and high-density virtualization.",
    description: "2U Rackmount Dual Socket PCIe Gen5\n\nKey features: Cyber Resilient Architecture\nTypical applications: AI Training / Core Banking\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 3-Year ProSupport Plus with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: NVMe-ready architecture for ultra-low latency workloads\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 1250000.00,
    warranty: "3-Year ProSupport Plus",
    imageFile: "/images/dell-r760.jpg",
    isFeatured: true,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Platinum 8480+" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "512GB DDR5-4800 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "8x 3.2TB NVMe U.2 SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H965i" },
      { name: "network", label: "Network", sortOrder: 4, value: "Broadcom 57504 Quad 10/25GbE" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 2400W Titanium" },
    ],
  },
  {
    sku: "PE-R660",
    name: "Dell PowerEdge R660",
    slug: "dell-r660",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "High-density 1U two-socket server for maximum performance.",
    description: "1U Rackmount Dual Socket\n\nKey features: Advanced liquid cooling options\nTypical applications: High-Frequency Trading\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 3-Year ProSupport Plus with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: versatile SAS/SATA support for mixed workload environments\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 820000.00,
    warranty: "3-Year ProSupport Plus",
    imageFile: "/images/dell-r660.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6430" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "256GB DDR5-4800 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 1.92TB SAS 24Gbps SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H755N" },
      { name: "network", label: "Network", sortOrder: 4, value: "Intel E810-XXV Dual 25GbE" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 1400W Platinum" },
    ],
  },
  {
    sku: "PE-R360",
    name: "Dell PowerEdge R360",
    slug: "dell-r360",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "Entry-level 1U single-socket server for SMBs.",
    description: "1U Rackmount Single Socket\n\nKey features: Cost-effective edge computing\nTypical applications: SMB IT / File Serving\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 3-Year Basic with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 185000.00,
    warranty: "3-Year Basic",
    imageFile: "/images/dell-r360.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Xeon E-2300 series" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "64GB DDR4 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "2x 2TB SATA HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H345" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual 1GbE On-Board" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Single 600W Platinum" },
    ],
  },
  {
    sku: "PE-R930",
    name: "Dell PowerEdge R930",
    slug: "dell-r930",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "Legacy 4U quad-socket server for massive in-memory databases.",
    description: "4U Rackmount Quad Socket\n\nKey features: Massive scalability\nTypical applications: In-memory databases (SAP HANA)\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 450000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-r930.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "4x Intel Xeon E7-8800 v4" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "1TB DDR4 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "12x 1.2TB SAS HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H730P" },
      { name: "network", label: "Network", sortOrder: 4, value: "Quad 10GbE SFP+" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Quad 1100W Platinum" },
    ],
  },
  {
    sku: "PE-R830",
    name: "Dell PowerEdge R830",
    slug: "dell-r830",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "Dense 2U quad-socket server for heavy virtualization.",
    description: "2U Rackmount Quad Socket\n\nKey features: Dense compute nodes\nTypical applications: Virtual Desktop Infrastructure\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: versatile SAS/SATA support for mixed workload environments\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 320000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-r830.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "4x Intel Xeon E5-4600 v4" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "512GB DDR4 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "8x 960GB SATA SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H730" },
      { name: "network", label: "Network", sortOrder: 4, value: "Quad 1GbE" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 1100W" },
    ],
  },
  {
    sku: "PE-R750",
    name: "Dell PowerEdge R750",
    slug: "dell-r750",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "15th Gen 2U workhorse for mainstream enterprise workloads.",
    description: "2U Rackmount Dual Socket\n\nKey features: PCIe Gen4 support\nTypical applications: General Enterprise IT\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 3-Year ProSupport with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 480000.00,
    warranty: "3-Year ProSupport",
    imageFile: "/images/dell-r750.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6330" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "256GB DDR4-3200 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 2.4TB SAS HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H745" },
      { name: "network", label: "Network", sortOrder: 4, value: "Broadcom Dual 10GbE" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 1400W Platinum" },
    ],
  },
  {
    sku: "PE-R650",
    name: "Dell PowerEdge R650",
    slug: "dell-r650",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "15th Gen 1U dense compute server.",
    description: "1U Rackmount Dual Socket\n\nKey features: NVMe optimization\nTypical applications: Cloud hosting\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 3-Year ProSupport with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: NVMe-ready architecture for ultra-low latency workloads\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 390000.00,
    warranty: "3-Year ProSupport",
    imageFile: "/images/dell-r650.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Silver 4314" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-3200 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "2x 1.92TB NVMe SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H745" },
      { name: "network", label: "Network", sortOrder: 4, value: "Broadcom Dual 10GbE" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 800W Platinum" },
    ],
  },
  {
    sku: "PE-R740XD",
    name: "Dell PowerEdge R740xd",
    slug: "dell-r740xd",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "Storage-heavy 2U server with maximum drive bays.",
    description: "2U Rackmount Dual Socket\n\nKey features: Extreme storage density\nTypical applications: Software Defined Storage\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 350000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-r740xd.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6248" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2933 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "12x 8TB NLSAS HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H740P" },
      { name: "network", label: "Network", sortOrder: 4, value: "Quad 10GbE Base-T" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 1100W Platinum" },
    ],
  },
  {
    sku: "PE-R440",
    name: "Dell PowerEdge R440",
    slug: "dell-r440",
    brand: "Dell EMC",
    categorySlug: "rack-servers",
    shortDesc: "Value-driven 1U dual-socket server.",
    description: "1U Rackmount Dual Socket\n\nKey features: Short-depth chassis\nTypical applications: Web serving\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 145000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-r440.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Silver 4210" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "64GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 1.2TB SAS HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H330" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual 1GbE" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 550W Platinum" },
    ],
  },
  {
    sku: "PE-T640",
    name: "Dell PowerEdge T640",
    slug: "dell-t640",
    brand: "Dell EMC",
    categorySlug: "tower-servers",
    shortDesc: "Scalable 5U tower for remote offices.",
    description: "5U Tower Dual Socket\n\nKey features: Rackable tower design\nTypical applications: Remote Office IT\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 210000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-t640.jpg",
    isFeatured: true,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Silver 4214" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "8x 4TB SATA HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H730P" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual 1GbE" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 750W Platinum" },
    ],
  },
  {
    sku: "PE-T440",
    name: "Dell PowerEdge T440",
    slug: "dell-t440",
    brand: "Dell EMC",
    categorySlug: "tower-servers",
    shortDesc: "Mid-level tower server for growing businesses.",
    description: "5U Tower Dual Socket\n\nKey features: Quiet acoustics\nTypical applications: Small Business Server\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 115000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-t440.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Xeon Bronze 3204" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "32GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 2TB SATA HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "PERC H330" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual 1GbE" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Single 495W" },
    ],
  },
  {
    sku: "DL360-G10P",
    name: "HPE ProLiant DL360 Gen10 Plus",
    slug: "hpe-dl360-g10p",
    brand: "HPE",
    categorySlug: "rack-servers",
    shortDesc: "Enhanced 1U server with PCIe Gen4 and Intel 3rd Gen.",
    description: "1U Rackmount Dual Socket\n\nKey features: Silicon Root of Trust\nTypical applications: Dense Virtualization\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 3-Year Warranty with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: NVMe-ready architecture for ultra-low latency workloads\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 460000.00,
    warranty: "3-Year Warranty",
    imageFile: "/images/hp-dl360-g10p.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6330" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "256GB DDR4-3200 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 1.92TB NVMe SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HPE Smart Array P408i-a" },
      { name: "network", label: "Network", sortOrder: 4, value: "HPE 10GbE 2-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 800W Flex Slot" },
    ],
  },
  {
    sku: "DL365-G10P",
    name: "HPE ProLiant DL365 Gen10 Plus",
    slug: "hpe-dl365-g10p",
    brand: "HPE",
    categorySlug: "rack-servers",
    shortDesc: "AMD EPYC powered 1U dense compute server.",
    description: "1U Rackmount Dual Socket\n\nKey features: AMD Infinity Architecture\nTypical applications: VDI / Edge Computing\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 3-Year Warranty with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: versatile SAS/SATA support for mixed workload environments\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 485000.00,
    warranty: "3-Year Warranty",
    imageFile: "/images/hp-dl365-g10p.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x AMD EPYC 7313" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "256GB DDR4-3200 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 3.84TB SAS SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HPE Smart Array P816i-a" },
      { name: "network", label: "Network", sortOrder: 4, value: "HPE 10/25GbE 2-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 800W Flex Slot" },
    ],
  },
  {
    sku: "DL345-G10P",
    name: "HPE ProLiant DL345 Gen10 Plus",
    slug: "hpe-dl345-g10p",
    brand: "HPE",
    categorySlug: "rack-servers",
    shortDesc: "Single-socket 2U AMD server for storage workloads.",
    description: "2U Rackmount Single Socket\n\nKey features: High storage capacity per CPU\nTypical applications: Database workloads\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 3-Year Warranty with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 320000.00,
    warranty: "3-Year Warranty",
    imageFile: "/images/hp-dl345-g10p.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x AMD EPYC 7443P" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-3200 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "8x 8TB NLSAS HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HPE Smart Array P408i-a" },
      { name: "network", label: "Network", sortOrder: 4, value: "HPE 10GbE 2-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 800W Flex Slot" },
    ],
  },
  {
    sku: "DL560-G10",
    name: "HPE ProLiant DL560 Gen10",
    slug: "hpe-dl560-g10",
    brand: "HPE",
    categorySlug: "rack-servers",
    shortDesc: "4-socket 2U scale-up server for critical databases.",
    description: "2U Rackmount Quad Socket\n\nKey features: Massive scale-up capability\nTypical applications: SAP HANA\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: versatile SAS/SATA support for mixed workload environments\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 650000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-dl560-g10.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "4x Intel Xeon Platinum 8268" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "512GB DDR4-2933 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "8x 1.92TB SAS SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HPE Smart Array P816i-a" },
      { name: "network", label: "Network", sortOrder: 4, value: "HPE 10/25GbE 2-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 1600W Flex Slot" },
    ],
  },
  {
    sku: "DL380-G10",
    name: "HPE ProLiant DL380 Gen10",
    slug: "hpe-dl380-g10",
    brand: "HPE",
    categorySlug: "rack-servers",
    shortDesc: "Flagship 2U server offering unmatched security and performance.",
    description: "2U Rackmount Dual Socket\n\nKey features: iLO 5 Advanced\nTypical applications: Virtualization\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 295000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-dl380-g10.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6230" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2933 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 1.2TB SAS HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HPE Smart Array P408i-a" },
      { name: "network", label: "Network", sortOrder: 4, value: "HPE 1GbE 4-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 800W Flex Slot" },
    ],
  },
  {
    sku: "DL360-G10",
    name: "HPE ProLiant DL360 Gen10",
    slug: "hpe-dl360-g10",
    brand: "HPE",
    categorySlug: "rack-servers",
    shortDesc: "Dense 1U compute powerhouse.",
    description: "1U Rackmount Dual Socket\n\nKey features: Space-saving 1U\nTypical applications: Hyperconverged Infrastructure\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: versatile SAS/SATA support for mixed workload environments\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 240000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-dl360-g10.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 5218" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "2x 960GB SATA SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HPE Smart Array P408i-a" },
      { name: "network", label: "Network", sortOrder: 4, value: "HPE 10GbE 2-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 500W Flex Slot" },
    ],
  },
  {
    sku: "DL380-G9",
    name: "HP ProLiant DL380 Gen9",
    slug: "hp-dl380-g9",
    brand: "HP",
    categorySlug: "rack-servers",
    shortDesc: "Highly reliable 2U workhorse for budget deployments.",
    description: "2U Rackmount Dual Socket\n\nKey features: iLO 4 Management\nTypical applications: Backup server\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 110000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-dl380-g9.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon E5-2699 v4" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2400 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 1.2TB SAS HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HP Smart Array P440ar" },
      { name: "network", label: "Network", sortOrder: 4, value: "HP 1GbE 4-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 500W Platinum" },
    ],
  },
  {
    sku: "DL360-G9",
    name: "HP ProLiant DL360 Gen9",
    slug: "hp-dl360-g9",
    brand: "HP",
    categorySlug: "rack-servers",
    shortDesc: "Budget-friendly 1U server.",
    description: "1U Rackmount Dual Socket\n\nKey features: Cost-effective computing\nTypical applications: DNS Server / Firewall\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: versatile SAS/SATA support for mixed workload environments\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 75000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-dl360-g9.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon E5-2680 v4" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "64GB DDR4-2400 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "2x 480GB SATA SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HP Smart Array P440ar" },
      { name: "network", label: "Network", sortOrder: 4, value: "HP 1GbE 4-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 500W Platinum" },
    ],
  },
  {
    sku: "DL160-G9",
    name: "HP ProLiant DL160 Gen9",
    slug: "hp-dl160-g9",
    brand: "HP",
    categorySlug: "rack-servers",
    shortDesc: "Entry 1U dual-socket server for space-constrained setups.",
    description: "1U Rackmount Dual Socket\n\nKey features: Ultra-low budget\nTypical applications: Basic IT Infrastructure\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 45000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-dl160-g9.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon E5-2620 v4" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "32GB DDR4-2400 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "2x 1TB SATA HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HP Smart Array B140i" },
      { name: "network", label: "Network", sortOrder: 4, value: "HP 1GbE 2-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Single 500W" },
    ],
  },
  {
    sku: "DL380P-G8",
    name: "HP ProLiant DL380p Gen8",
    slug: "hp-dl380p-g8",
    brand: "HP",
    categorySlug: "rack-servers",
    shortDesc: "Legacy 2U server for basic computing needs.",
    description: "2U Rackmount Dual Socket\n\nKey features: DDR3 Support\nTypical applications: Test environments\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 90-Day Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: high-capacity HDD support for bulk data retention",
    basePrice: 35000.00,
    warranty: "90-Day Refurbished",
    imageFile: "/images/hp-dl380p-g8.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon E5-2670 v2" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "64GB DDR3 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 600GB SAS HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "HP Smart Array P420i" },
      { name: "network", label: "Network", sortOrder: 4, value: "HP 1GbE 4-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 460W" },
    ],
  },
  {
    sku: "7X06-SR650",
    name: "Lenovo ThinkSystem SR650",
    slug: "lenovo-sr650",
    brand: "Lenovo",
    categorySlug: "rack-servers",
    shortDesc: "Flagship 2U server with AnyBay storage architecture.",
    description: "2U Rackmount Dual Socket\n\nKey features: AnyBay Drive Bays\nTypical applications: Enterprise Resource Planning\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: versatile SAS/SATA support for mixed workload environments\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 310000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/lenovo-sr650.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6248" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "256GB TruDDR4-2933 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "8x 3.84TB SAS SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "ThinkSystem RAID 930-8i" },
      { name: "network", label: "Network", sortOrder: 4, value: "ThinkSystem 10Gb 4-port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 750W Platinum" },
    ],
  },
  {
    sku: "7X02-SR630",
    name: "Lenovo ThinkSystem SR630",
    slug: "lenovo-sr630",
    brand: "Lenovo",
    categorySlug: "rack-servers",
    shortDesc: "Highly versatile 1U rack server.",
    description: "1U Rackmount Dual Socket\n\nKey features: XClarity Provisioning\nTypical applications: Web Hosting\n\nGPU support: Optional GPU acceleration support for AI, visualization, and accelerated workloads\nExpansion slots: Multiple PCIe Gen4/Gen5 expansion slots for NICs, HBAs, and accelerators\nI/O ports: USB, serial, VGA/DisplayPort, and high-speed Ethernet connectivity\nCooling & airflow: Optimized airflow with hot-swap fans and front-to-back cooling design\nWarranty: 1-Year Refurbished with firmware support, remote diagnostics, and replacement coverage\n\nManagement: remote monitoring, firmware updates, and lifecycle automation\nSecurity: TPM 2.0, secure boot, and chassis protection support\nExpandability: PCIe expansion slots and flexible storage configuration\nPower: efficient high-density PSU design with redundancy support\nStorage: versatile SAS/SATA support for mixed workload environments\nMemory: ECC registered memory with enterprise-class reliability",
    basePrice: 220000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/lenovo-sr630.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Silver 4214" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB TruDDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "4x 960GB SATA SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "ThinkSystem RAID 730-8i" },
      { name: "network", label: "Network", sortOrder: 4, value: "Intel I350 1GbE 4-Port" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Dual 550W Platinum" },
    ],
  },
  {
    sku: "PREC-7920",
    name: "Dell Precision 7920 Tower",
    slug: "dell-7920",
    brand: "Dell",
    categorySlug: "workstations",
    shortDesc: "Ultimate dual-socket workstation for extreme rendering.",
    description: "Full Tower Dual Socket\n\nKey features: Dell Optimizer\nTypical applications: AI / Deep Learning\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 350000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-7920.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6230" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "256GB DDR4-2933 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "2TB NVMe + 2x 4TB HDDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1400W 80 Plus Gold" },
    ],
  },
  {
    sku: "PREC-7820",
    name: "Dell Precision 7820 Tower",
    slug: "dell-7820",
    brand: "Dell",
    categorySlug: "workstations",
    shortDesc: "Compact dual-socket workstation.",
    description: "Mid-Tower Dual Socket\n\nKey features: Tool-less chassis\nTypical applications: CAD/CAM\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 210000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-7820.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Silver 4214" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "1TB NVMe + 1x 2TB HDD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "950W 80 Plus Gold" },
    ],
  },
  {
    sku: "PREC-5820",
    name: "Dell Precision 5820 Tower",
    slug: "dell-5820",
    brand: "Dell",
    categorySlug: "workstations",
    shortDesc: "Mainstream single-socket workstation.",
    description: "Mid-Tower Single Socket\n\nKey features: Front-accessible drives\nTypical applications: 4K Video Editing\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 165000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-5820.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Xeon W-2295" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "64GB DDR4-2933 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "1TB NVMe PCIe SSD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "950W" },
    ],
  },
  {
    sku: "PREC-3630",
    name: "Dell Precision 3630 Tower",
    slug: "dell-3630",
    brand: "Dell",
    categorySlug: "workstations",
    shortDesc: "Entry-level compact workstation.",
    description: "Mini-Tower Single Socket\n\nKey features: Space-saving design\nTypical applications: 2D CAD / Web Dev\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 65000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-3630.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Core i7-9700K" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "32GB DDR4-2666 Non-ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "512GB NVMe + 1TB HDD" },
      { name: "network", label: "Network", sortOrder: 4, value: "Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "460W" },
    ],
  },
  {
    sku: "PREC-7910",
    name: "Dell Precision 7910 Tower",
    slug: "dell-7910",
    brand: "Dell",
    categorySlug: "workstations",
    shortDesc: "Legacy heavy-duty dual-socket workstation.",
    description: "Full Tower Dual Socket\n\nKey features: Massive expansion\nTypical applications: Legacy VFX Rendering\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation",
    basePrice: 125000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-7910.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon E5-2680 v4" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2400 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "1TB SSD + 2TB HDD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1300W" },
    ],
  },
  {
    sku: "PREC-5810",
    name: "Dell Precision 5810 Tower",
    slug: "dell-5810",
    brand: "Dell",
    categorySlug: "workstations",
    shortDesc: "Legacy mainstream workstation.",
    description: "Mid-Tower Single Socket\n\nKey features: Affordable pro performance\nTypical applications: Student Engineering\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation",
    basePrice: 45000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/dell-5810.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Xeon E5-1650 v4" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "32GB DDR4-2400 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "512GB SSD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "685W" },
    ],
  },
  {
    sku: "Z8-G4",
    name: "HP Z8 G4 Workstation",
    slug: "hp-z8-g4",
    brand: "HP",
    categorySlug: "workstations",
    shortDesc: "Most powerful HP desktop for 8K editing.",
    description: "Full Tower Dual Socket\n\nKey features: Split-chassis thermal routing\nTypical applications: VFX / 8K Video\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation",
    basePrice: 380000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-z8-g4.jpg",
    isFeatured: true,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6136" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "192GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "1TB Z Turbo Drive + 4TB HDD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual 10GbE LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1125W" },
    ],
  },
  {
    sku: "Z6-G4",
    name: "HP Z6 G4 Workstation",
    slug: "hp-z6-g4",
    brand: "HP",
    categorySlug: "workstations",
    shortDesc: "Highly scalable powerhouse workstation.",
    description: "Mid-Tower Dual Socket\n\nKey features: Whisper-quiet acoustics\nTypical applications: 3D Rendering\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 215000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-z6-g4.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Silver 4114" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2400 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "1TB NVMe + 2TB HDD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1000W" },
    ],
  },
  {
    sku: "Z4-G4",
    name: "HP Z4 G4 Workstation",
    slug: "hp-z4-g4",
    brand: "HP",
    categorySlug: "workstations",
    shortDesc: "Best-selling performance workstation.",
    description: "Mid-Tower Single Socket\n\nKey features: Dust filter options\nTypical applications: BIM / Architecture\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 140000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-z4-g4.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Xeon W-2145" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "64GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "1TB Z Turbo Drive NVMe" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "750W" },
    ],
  },
  {
    sku: "Z2-G4",
    name: "HP Z2 G4 Workstation",
    slug: "hp-z2-g4",
    brand: "HP",
    categorySlug: "workstations",
    shortDesc: "Entry-level powerhouse in a compact tower.",
    description: "Mini-Tower Single Socket\n\nKey features: ISV Certified\nTypical applications: Graphic Design\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 55000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-z2-g4.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Core i7-8700" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "32GB DDR4 Non-ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "512GB NVMe SSD" },
      { name: "network", label: "Network", sortOrder: 4, value: "Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "500W" },
    ],
  },
  {
    sku: "Z840",
    name: "HP Z840 Workstation",
    slug: "hp-z840",
    brand: "HP",
    categorySlug: "workstations",
    shortDesc: "Robust legacy workstation with massive core counts.",
    description: "Full Tower Dual Socket\n\nKey features: Heavy-duty build\nTypical applications: Audio Production\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation",
    basePrice: 120000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/hp-z840.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon E5-2690 v4" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2400 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "1TB SSD + 4TB HDD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1125W" },
    ],
  },
  {
    sku: "TS-P920",
    name: "Lenovo ThinkStation P920",
    slug: "lenovo-p920",
    brand: "Lenovo",
    categorySlug: "workstations",
    shortDesc: "Extreme computing tasks with immense storage.",
    description: "Full Tower Dual Socket\n\nKey features: Tri-channel cooling\nTypical applications: Big Data / High-end VFX\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 330000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/lenovo-p920.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Gold 6136" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "192GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "2x 1TB NVMe M.2 SSDs" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "NVMe RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1400W" },
    ],
  },
  {
    sku: "TS-P720",
    name: "Lenovo ThinkStation P720",
    slug: "lenovo-p720",
    brand: "Lenovo",
    categorySlug: "workstations",
    shortDesc: "Versatile dual-processor workstation.",
    description: "Mid-Tower Dual Socket\n\nKey features: Red touch-points\nTypical applications: Financial Modeling\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 195000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/lenovo-p720.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2x Intel Xeon Silver 4114" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4-2400 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "1TB NVMe + 2TB HDD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Dual Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "900W" },
    ],
  },
  {
    sku: "TS-P520",
    name: "Lenovo ThinkStation P520",
    slug: "lenovo-p520",
    brand: "Lenovo",
    categorySlug: "workstations",
    shortDesc: "Mainstream single-socket workstation.",
    description: "Mid-Tower Single Socket\n\nKey features: Lenovo Performance Tuner\nTypical applications: Medium 3D Design\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 110000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/lenovo-p520.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Xeon W-2133" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "64GB DDR4-2666 ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "512GB NVMe M.2 SSD" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "SATA RAID" },
      { name: "network", label: "Network", sortOrder: 4, value: "Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "690W" },
    ],
  },
  {
    sku: "TS-P330",
    name: "Lenovo ThinkStation P330",
    slug: "lenovo-p330",
    brand: "Lenovo",
    categorySlug: "workstations",
    shortDesc: "Reliable entry-level workstation.",
    description: "Tower Single Socket\n\nKey features: Low power consumption\nTypical applications: Healthcare Admin\n\nGPU support: Professional GPU support with multi-display and accelerator-ready architecture\nExpansion slots: Multiple PCIe slots for graphics, storage, and I/O expansion\nI/O ports: USB 3.x, Thunderbolt-capable ports, display outputs, and Ethernet connectivity\nCooling & airflow: Quiet cooling design with efficient airflow for sustained workstation loads\nWarranty: 1-Year Refurbished with platform support and parts replacement coverage\n\nGraphics: supports professional GPU acceleration and multi-display setups\nExpansion: PCIe slot flexibility for high-end workstation add-ons\nConnectivity: USB, Ethernet, and display outputs for studio workflows\nReliability: ECC memory, ISV-ready design, and quiet operation\nStorage: fast SSD caching and large-capacity local storage",
    basePrice: 55000.00,
    warranty: "1-Year Refurbished",
    imageFile: "/images/lenovo-p330.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "1x Intel Core i7-8700" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "32GB DDR4-2666 Non-ECC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "512GB NVMe SSD" },
      { name: "network", label: "Network", sortOrder: 4, value: "Gigabit LAN" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "400W" },
    ],
  },
  {
    sku: "CD8069504228001",
    name: "Intel Xeon Platinum 8280",
    slug: "intel-8280",
    brand: "Intel",
    categorySlug: "processors",
    shortDesc: "Top-tier 2nd Gen scalable processor.",
    description: "28 Cores 56 Threads 38.5MB L3\n\nKey features: Deep Learning Boost\nTypical applications: Data Center upgrades\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 90-Day with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds\nMemory: high-density ECC memory support for mission-critical environments",
    basePrice: 145000.00,
    warranty: "90-Day",
    imageFile: "/images/intel-8280.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2.70 GHz Base" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "Up to 1TB DDR4" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "205W TDP" },
    ],
  },
  {
    sku: "CD8069504449000",
    name: "Intel Xeon Gold 6248R",
    slug: "intel-6248r",
    brand: "Intel",
    categorySlug: "processors",
    shortDesc: "High-frequency processor for databases.",
    description: "24 Cores 48 Threads 35.75MB L3\n\nKey features: Turbo Boost 2.0\nTypical applications: HPC\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 90-Day with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds\nMemory: high-density ECC memory support for mission-critical environments",
    basePrice: 75000.00,
    warranty: "90-Day",
    imageFile: "/images/intel-6248r.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "3.00 GHz Base" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "Up to 1TB DDR4" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "205W TDP" },
    ],
  },
  {
    sku: "CD8069504343700",
    name: "Intel Xeon Silver 4214R",
    slug: "intel-4214r",
    brand: "Intel",
    categorySlug: "processors",
    shortDesc: "Mid-tier processor for general IT.",
    description: "12 Cores 24 Threads 16.5MB L3\n\nKey features: Hyper-Threading\nTypical applications: General Virtualization\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 90-Day with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds\nMemory: high-density ECC memory support for mission-critical environments",
    basePrice: 35000.00,
    warranty: "90-Day",
    imageFile: "/images/intel-4214r.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2.40 GHz Base" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "Up to 1TB DDR4" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "100W TDP" },
    ],
  },
  {
    sku: "100-000000053",
    name: "AMD EPYC 7742",
    slug: "amd-7742",
    brand: "AMD",
    categorySlug: "processors",
    shortDesc: "Massive 64-core processor for cloud.",
    description: "64 Cores 128 Threads 256MB L3\n\nKey features: PCIe Gen 4.0 support\nTypical applications: Dense virtualization\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 90-Day with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds\nMemory: high-density ECC memory support for mission-critical environments",
    basePrice: 185000.00,
    warranty: "90-Day",
    imageFile: "/images/amd-7742.jpg",
    isFeatured: true,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "2.25 GHz Base" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "Up to 4TB DDR4" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "225W TDP" },
    ],
  },
  {
    sku: "M386AAG40MMB",
    name: "128GB DDR4-3200 LRDIMM",
    slug: "128gb-ram",
    brand: "Samsung",
    categorySlug: "memory",
    shortDesc: "High-density load-reduced memory.",
    description: "128GB Quad Rank 288-pin\n\nKey features: ECC / Load-Reduced\nTypical applications: In-memory databases\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: Lifetime with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds\nMemory: high-density ECC memory support for mission-critical environments",
    basePrice: 35000.00,
    warranty: "Lifetime",
    imageFile: "/images/128gb-ram.jpg",
    isFeatured: true,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Compatible Intel/AMD" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "128GB DDR4 3200MT/s" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1.2 Volts" },
    ],
  },
  {
    sku: "HMAA8GR7AJR4N",
    name: "64GB DDR4-2933 RDIMM",
    slug: "64gb-ram",
    brand: "SK Hynix",
    categorySlug: "memory",
    shortDesc: "Standard high-density enterprise memory.",
    description: "64GB Dual Rank 288-pin\n\nKey features: Registered ECC\nTypical applications: General virtualization\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: Lifetime with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds\nMemory: high-density ECC memory support for mission-critical environments",
    basePrice: 15000.00,
    warranty: "Lifetime",
    imageFile: "/images/64gb-ram.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Compatible Intel/AMD" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "64GB DDR4 2933MT/s" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1.2 Volts" },
    ],
  },
  {
    sku: "MTA36ASF4G72PZ",
    name: "32GB DDR4-2666 RDIMM",
    slug: "32gb-ram",
    brand: "Micron",
    categorySlug: "memory",
    shortDesc: "Cost-effective memory for legacy systems.",
    description: "32GB Dual Rank 288-pin\n\nKey features: Registered ECC\nTypical applications: Budget server builds\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: Lifetime with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds\nMemory: high-density ECC memory support for mission-critical environments",
    basePrice: 6500.00,
    warranty: "Lifetime",
    imageFile: "/images/32gb-ram.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Compatible Intel/AMD" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "32GB DDR4 2666MT/s" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1.2 Volts" },
    ],
  },
  {
    sku: "KSM24RS4/16HAI",
    name: "16GB DDR4-2400 RDIMM",
    slug: "16gb-ram",
    brand: "Kingston",
    categorySlug: "memory",
    shortDesc: "Entry-level server memory.",
    description: "16GB Single Rank 288-pin\n\nKey features: Registered ECC\nTypical applications: Basic IT\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: Lifetime with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds\nMemory: high-density ECC memory support for mission-critical environments",
    basePrice: 3200.00,
    warranty: "Lifetime",
    imageFile: "/images/16gb-ram.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Compatible Intel/AMD" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "16GB DDR4 2400MT/s" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "1.2 Volts" },
    ],
  },
  {
    sku: "405-AAWS",
    name: "Dell PERC H740P",
    slug: "perc-h740p",
    brand: "Dell",
    categorySlug: "raid-controllers",
    shortDesc: "Hardware RAID for 14th Gen Dell.",
    description: "PCIe 3.0 x8\n\nKey features: Battery-backed cache\nTypical applications: Dell R740 storage\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 38000.00,
    warranty: "1-Year",
    imageFile: "/images/perc-h740p.jpg",
    isFeatured: true,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Broadcom ROC" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "8GB NV Cache" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "SAS/SATA" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "RAID 0/1/5/6/10/50/60" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Slot powered" },
    ],
  },
  {
    sku: "804331-B21",
    name: "HPE Smart Array P408i-a",
    slug: "hp-p408i",
    brand: "HPE",
    categorySlug: "raid-controllers",
    shortDesc: "Modular RAID for HP Gen10.",
    description: "Type-a modular\n\nKey features: Secure Encryption\nTypical applications: HP DL380 storage\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 28000.00,
    warranty: "1-Year",
    imageFile: "/images/hp-p408i.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Microchip ROC" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "2GB FBWC" },
      { name: "storage", label: "Storage", sortOrder: 2, value: "SAS/SATA" },
      { name: "raid", label: "RAID Controller", sortOrder: 3, value: "RAID 0/1/5/6/10/50/60" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Slot powered" },
    ],
  },
  {
    sku: "BCM57416",
    name: "Broadcom 57416 Dual Port",
    slug: "bcm57416",
    brand: "Broadcom",
    categorySlug: "network-cards",
    shortDesc: "Dual-port 10 Gigabit Base-T adapter.",
    description: "PCIe 3.0 x8\n\nKey features: RoCE support\nTypical applications: Data center networking\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 18000.00,
    warranty: "1-Year",
    imageFile: "/images/bcm57416.jpg",
    isFeatured: true,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "BCM57416 MAC" },
      { name: "network", label: "Network", sortOrder: 4, value: "2x 10GbE BASE-T" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "Slot powered" },
    ],
  },
  {
    sku: "VCNRTXA6000",
    name: "NVIDIA RTX A6000",
    slug: "rtx-a6000",
    brand: "NVIDIA",
    categorySlug: "workstation-gpus",
    shortDesc: "Ampere GPU for real-time ray tracing.",
    description: "10752 CUDA Cores PCIe 4.0\n\nKey features: NVLink support\nTypical applications: Deep Learning\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 385000.00,
    warranty: "1-Year",
    imageFile: "/images/rtx-a6000.jpg",
    isFeatured: true,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Ampere GPU" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "48GB GDDR6 ECC" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "300W" },
    ],
  },
  {
    sku: "VCNRTXA5000",
    name: "NVIDIA RTX A5000",
    slug: "rtx-a5000",
    brand: "NVIDIA",
    categorySlug: "workstation-gpus",
    shortDesc: "Balanced power for 3D animation.",
    description: "8192 CUDA Cores PCIe 4.0\n\nKey features: 256 Tensor Cores\nTypical applications: 3D Animation\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 195000.00,
    warranty: "1-Year",
    imageFile: "/images/rtx-a5000.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Ampere GPU" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "24GB GDDR6 ECC" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "230W" },
    ],
  },
  {
    sku: "VCNRTXA4000",
    name: "NVIDIA RTX A4000",
    slug: "rtx-a4000",
    brand: "NVIDIA",
    categorySlug: "workstation-gpus",
    shortDesc: "Single-slot powerhouse for CAD.",
    description: "6144 CUDA Cores PCIe 4.0\n\nKey features: Single-slot design\nTypical applications: Architectural CAD\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 95000.00,
    warranty: "1-Year",
    imageFile: "/images/rtx-a4000.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Ampere GPU" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "16GB GDDR6 ECC" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "140W" },
    ],
  },
  {
    sku: "VCQRTX8000",
    name: "NVIDIA Quadro RTX 8000",
    slug: "rtx-8000",
    brand: "NVIDIA",
    categorySlug: "workstation-gpus",
    shortDesc: "Legacy flagship Turing GPU.",
    description: "4608 CUDA Cores PCIe 3.0\n\nKey features: VirtualLink\nTypical applications: Medical imaging\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 240000.00,
    warranty: "1-Year",
    imageFile: "/images/rtx-8000.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Turing GPU" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "48GB GDDR6 ECC" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "295W" },
    ],
  },
  {
    sku: "VCQRTX4000",
    name: "NVIDIA Quadro RTX 4000",
    slug: "rtx-4000",
    brand: "NVIDIA",
    categorySlug: "workstation-gpus",
    shortDesc: "Mainstream Turing professional graphics.",
    description: "2304 CUDA Cores PCIe 3.0\n\nKey features: VR Ready\nTypical applications: Video Editing\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 75000.00,
    warranty: "1-Year",
    imageFile: "/images/rtx-4000.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "Turing GPU" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "8GB GDDR6" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "160W" },
    ],
  },
  {
    sku: "100-506157",
    name: "AMD Radeon Pro W6800",
    slug: "amd-w6800",
    brand: "AMD",
    categorySlug: "workstation-gpus",
    shortDesc: "RDNA 2 architecture heavy-duty GPU.",
    description: "3840 Stream Processors PCIe 4.0\n\nKey features: Hardware Raytracing\nTypical applications: VFX / Broadcasting\n\nGPU support: No dedicated GPU; supports host-based graphics and accelerator integration\nExpansion slots: PCIe slot support for RAID, NIC, and controller upgrades\nI/O ports: Standard storage and network interfaces for enterprise system integration\nCooling & airflow: Passive or low-profile cooling suitable for dense infrastructure environments\nWarranty: 1-Year with replacement support and compatibility assurance\n\nCompatibility: enterprise platform support for Intel and AMD systems\nReliability: tested for data-center uptime and long-term deployment\nDeployment: suitable for upgrades, expansions, and custom server builds",
    basePrice: 175000.00,
    warranty: "1-Year",
    imageFile: "/images/amd-w6800.jpg",
    isFeatured: false,
    groups: [
      { name: "processor", label: "Processor", sortOrder: 0, value: "RDNA 2 GPU" },
      { name: "ram", label: "RAM", sortOrder: 1, value: "32GB GDDR6 ECC" },
      { name: "power-supply", label: "Power Supply", sortOrder: 5, value: "250W" },
    ],
  },
];
